"""initial_schema

Revision ID: 4da4206958b9
Revises: 
Create Date: 2026-01-08 13:34:21.879764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4da4206958b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_sheets',
    sa.Column('quote_id', sa.UUID(), nullable=False, comment='报价单ID'),
    sa.Column('quote_no', sa.String(length=50), nullable=False, comment='报价单编号'),
    sa.Column('customer_name', sa.String(length=255), nullable=False, comment='客户名称'),
    sa.Column('project_name', sa.String(length=255), nullable=True, comment='项目名称'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='创建人ID或名称'),
    sa.Column('sales_name', sa.String(length=100), nullable=True, comment='销售负责人姓名'),
    sa.Column('customer_contact', sa.String(length=100), nullable=True, comment='客户联系人'),
    sa.Column('customer_email', sa.String(length=255), nullable=True, comment='客户邮箱'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('terms', sa.Text(), nullable=True, comment='条款说明'),
    sa.Column('global_discount_rate', sa.Numeric(precision=5, scale=4), nullable=False, comment='全局折扣率'),
    sa.Column('global_discount_remark', sa.String(length=255), nullable=True, comment='折扣备注说明'),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=6), nullable=True, comment='报价总金额(折后)'),
    sa.Column('total_original_amount', sa.Numeric(precision=20, scale=6), nullable=True, comment='报价总金额(折前)'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='币种'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True, comment='报价有效期'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('quote_id'),
    sa.UniqueConstraint('quote_no'),
    comment='报价单主表'
    )
    op.create_index('ix_quote_created_at', 'quote_sheets', ['created_at'], unique=False)
    op.create_index('ix_quote_created_by', 'quote_sheets', ['created_by'], unique=False)
    op.create_index('ix_quote_customer', 'quote_sheets', ['customer_name'], unique=False)
    op.create_index('ix_quote_no', 'quote_sheets', ['quote_no'], unique=False)
    op.create_index('ix_quote_status', 'quote_sheets', ['status'], unique=False)
    op.create_table('quote_discounts',
    sa.Column('discount_id', sa.UUID(), nullable=False, comment='折扣ID'),
    sa.Column('quote_id', sa.UUID(), nullable=False, comment='所属报价单'),
    sa.Column('discount_type', sa.String(length=50), nullable=True, comment='折扣类型'),
    sa.Column('discount_value', sa.String(length=20), nullable=True, comment='折扣值'),
    sa.Column('apply_reason', sa.String(length=255), nullable=True, comment='应用原因'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote_sheets.quote_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discount_id'),
    comment='折扣记录表'
    )
    op.create_index('ix_discount_quote', 'quote_discounts', ['quote_id'], unique=False)
    op.create_table('quote_items',
    sa.Column('item_id', sa.UUID(), nullable=False, comment='明细ID'),
    sa.Column('quote_id', sa.UUID(), nullable=False, comment='所属报价单'),
    sa.Column('product_code', sa.String(length=100), nullable=False, comment='产品代码'),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='产品名称'),
    sa.Column('region', sa.String(length=50), nullable=False, comment='地域代码'),
    sa.Column('region_name', sa.String(length=100), nullable=True, comment='地域显示名称'),
    sa.Column('modality', sa.String(length=50), nullable=False, comment='模态类型'),
    sa.Column('capability', sa.String(length=50), nullable=True, comment='能力类型'),
    sa.Column('model_type', sa.String(length=50), nullable=True, comment='模型类型'),
    sa.Column('context_spec', sa.String(length=50), nullable=True, comment='context规格'),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True, comment='预估输入tokens数量'),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True, comment='预估输出tokens数量'),
    sa.Column('inference_mode', sa.String(length=50), nullable=True, comment='推理方式'),
    sa.Column('spec_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='规格配置'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('duration_months', sa.Integer(), nullable=True, comment='时长(月)'),
    sa.Column('usage_estimation', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='用量估算'),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=6), nullable=True, comment='单价'),
    sa.Column('original_price', sa.Numeric(precision=20, scale=6), nullable=False, comment='原价(元)'),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=False, comment='单项折扣率'),
    sa.Column('final_price', sa.Numeric(precision=20, scale=6), nullable=False, comment='折后价(元)'),
    sa.Column('billing_unit', sa.String(length=50), nullable=False, comment='计费单位'),
    sa.Column('subtotal', sa.Numeric(precision=20, scale=6), nullable=True, comment='小计'),
    sa.Column('discount_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='折扣信息'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序顺序'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote_sheets.quote_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    comment='报价明细表'
    )
    op.create_index('ix_item_quote', 'quote_items', ['quote_id'], unique=False)
    op.create_index('ix_item_sort_order', 'quote_items', ['quote_id', 'sort_order'], unique=False)
    op.create_table('quote_versions',
    sa.Column('version_id', sa.UUID(), nullable=False, comment='版本ID'),
    sa.Column('quote_id', sa.UUID(), nullable=False, comment='所属报价单'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('change_type', sa.String(length=50), nullable=True, comment='变更类型'),
    sa.Column('changes_summary', sa.String(length=500), nullable=True, comment='变更摘要'),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='快照数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote_sheets.quote_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id'),
    comment='版本快照表'
    )
    op.create_index('ix_version_number', 'quote_versions', ['quote_id', 'version_number'], unique=False)
    op.create_index('ix_version_quote', 'quote_versions', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_version_quote', table_name='quote_versions')
    op.drop_index('ix_version_number', table_name='quote_versions')
    op.drop_table('quote_versions')
    op.drop_index('ix_item_sort_order', table_name='quote_items')
    op.drop_index('ix_item_quote', table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index('ix_discount_quote', table_name='quote_discounts')
    op.drop_table('quote_discounts')
    op.drop_index('ix_quote_status', table_name='quote_sheets')
    op.drop_index('ix_quote_no', table_name='quote_sheets')
    op.drop_index('ix_quote_customer', table_name='quote_sheets')
    op.drop_index('ix_quote_created_by', table_name='quote_sheets')
    op.drop_index('ix_quote_created_at', table_name='quote_sheets')
    op.drop_table('quote_sheets')
    # ### end Alembic commands ###
